spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile

  data:
    rest:
      base-path: /data-api

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 10

    #h2 database url console available only with spring dev tools in the runtime classpath
    #http://localhost:8080/h2-console